# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  emv_version = "paris"
  fuzz = { runs = 1_000 }
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.19"
  fs_permissions = [{ access = "write", path = "out" }]

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 125
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  optimism = "${OPTIMISM_RPC_URL}"
